/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GH_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GH_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GH_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GH_ENCODED_PEM": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GH_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JWT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "NEON_DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POSTHOG_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POSTHOG_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SENTRY_DSN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_BOT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SLACK_SIGNING_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TestSentry": {
      "name": string
      "type": "sst.aws.Function"
    }
    "api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "frontend": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "lambda-error-alerts": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}