import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Nav from "./nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-full min-w-[900px] overflow-x-auto">
          <Suspense>
            <Nav />
          </Suspense>
          {/* <header className="bg-white border-b border-gray-200">{subnav}</header> */}
          <main className="">
            <div className="max-w-7xl mx-auto py-6 px-7">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
