-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.slack_integration 
    RENAME COLUMN slack_team to slack_team_name;

ALTER TABLE IF EXISTS public.slack_integration
    ADD COLUMN slack_team_id text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.username_mappings 
    RENAME COLUMN slack_username to slack_user_id;

COMMENT ON COLUMN public.slack_integration.slack_team_id
    IS 'The Slack team id';


