-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.slack_integration 
    RENAME COLUMN public.slack_integration.team to public.slack_integration.team_id;

ALTER TABLE IF EXISTS public.slack_integration
    ADD COLUMN slack_team text COLLATE pg_catalog."default";

COMMENT ON COLUMN public.slack_integration.slack_team
    IS 'The Slack team name';

COMMENT ON COLUMN public.slack_integration.team_id
    IS 'Review Corral Team Id';
