/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AppRouteImport } from './routes/app'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LoginSetTokenRouteImport } from './routes/login/set-token'
import { Route as LoginErrorRouteImport } from './routes/login/error'
import { Route as AppDashboardRouteImport } from './routes/app/_dashboard'
import { Route as LandingPrivacyRouteImport } from './routes/_landing/privacy'
import { Route as LandingAnimationsRouteImport } from './routes/_landing/animations'
import { Route as LandingAboutRouteImport } from './routes/_landing/about'
import { Route as AppDashboardIndexRouteImport } from './routes/app/_dashboard/index'
import { Route as AppSlackInstallSuccessRouteImport } from './routes/app/slack/install/success'
import { Route as AppSlackInstallFailureRouteImport } from './routes/app/slack/install/failure'
import { Route as AppDashboardOrgOrgIdRouteImport } from './routes/app/_dashboard/org/$orgId'
import { Route as AppDashboardOrgOrgIdIndexRouteImport } from './routes/app/_dashboard/org/$orgId/index'
import { Route as AppDashboardOrgOrgIdPaymentSuccessRouteImport } from './routes/app/_dashboard/org/$orgId/payment/success'
import { Route as AppDashboardOrgOrgIdPaymentFailureRouteImport } from './routes/app/_dashboard/org/$orgId/payment/failure'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LoginSetTokenRoute = LoginSetTokenRouteImport.update({
  id: '/login/set-token',
  path: '/login/set-token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginErrorRoute = LoginErrorRouteImport.update({
  id: '/login/error',
  path: '/login/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AppRoute,
} as any)
const LandingPrivacyRoute = LandingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAnimationsRoute = LandingAnimationsRouteImport.update({
  id: '/animations',
  path: '/animations',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAboutRoute = LandingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LandingRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppSlackInstallSuccessRoute = AppSlackInstallSuccessRouteImport.update({
  id: '/slack/install/success',
  path: '/slack/install/success',
  getParentRoute: () => AppRoute,
} as any)
const AppSlackInstallFailureRoute = AppSlackInstallFailureRouteImport.update({
  id: '/slack/install/failure',
  path: '/slack/install/failure',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardOrgOrgIdRoute = AppDashboardOrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardOrgOrgIdIndexRoute =
  AppDashboardOrgOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDashboardOrgOrgIdRoute,
  } as any)
const AppDashboardOrgOrgIdPaymentSuccessRoute =
  AppDashboardOrgOrgIdPaymentSuccessRouteImport.update({
    id: '/payment/success',
    path: '/payment/success',
    getParentRoute: () => AppDashboardOrgOrgIdRoute,
  } as any)
const AppDashboardOrgOrgIdPaymentFailureRoute =
  AppDashboardOrgOrgIdPaymentFailureRouteImport.update({
    id: '/payment/failure',
    path: '/payment/failure',
    getParentRoute: () => AppDashboardOrgOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppDashboardRouteWithChildren
  '/logout': typeof LogoutRoute
  '/about': typeof LandingAboutRoute
  '/animations': typeof LandingAnimationsRoute
  '/privacy': typeof LandingPrivacyRoute
  '/login/error': typeof LoginErrorRoute
  '/login/set-token': typeof LoginSetTokenRoute
  '/': typeof LandingIndexRoute
  '/login': typeof LoginIndexRoute
  '/app/': typeof AppDashboardIndexRoute
  '/app/org/$orgId': typeof AppDashboardOrgOrgIdRouteWithChildren
  '/app/slack/install/failure': typeof AppSlackInstallFailureRoute
  '/app/slack/install/success': typeof AppSlackInstallSuccessRoute
  '/app/org/$orgId/': typeof AppDashboardOrgOrgIdIndexRoute
  '/app/org/$orgId/payment/failure': typeof AppDashboardOrgOrgIdPaymentFailureRoute
  '/app/org/$orgId/payment/success': typeof AppDashboardOrgOrgIdPaymentSuccessRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppDashboardIndexRoute
  '/logout': typeof LogoutRoute
  '/about': typeof LandingAboutRoute
  '/animations': typeof LandingAnimationsRoute
  '/privacy': typeof LandingPrivacyRoute
  '/login/error': typeof LoginErrorRoute
  '/login/set-token': typeof LoginSetTokenRoute
  '/': typeof LandingIndexRoute
  '/login': typeof LoginIndexRoute
  '/app/slack/install/failure': typeof AppSlackInstallFailureRoute
  '/app/slack/install/success': typeof AppSlackInstallSuccessRoute
  '/app/org/$orgId': typeof AppDashboardOrgOrgIdIndexRoute
  '/app/org/$orgId/payment/failure': typeof AppDashboardOrgOrgIdPaymentFailureRoute
  '/app/org/$orgId/payment/success': typeof AppDashboardOrgOrgIdPaymentSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_landing/about': typeof LandingAboutRoute
  '/_landing/animations': typeof LandingAnimationsRoute
  '/_landing/privacy': typeof LandingPrivacyRoute
  '/app/_dashboard': typeof AppDashboardRouteWithChildren
  '/login/error': typeof LoginErrorRoute
  '/login/set-token': typeof LoginSetTokenRoute
  '/_landing/': typeof LandingIndexRoute
  '/login/': typeof LoginIndexRoute
  '/app/_dashboard/': typeof AppDashboardIndexRoute
  '/app/_dashboard/org/$orgId': typeof AppDashboardOrgOrgIdRouteWithChildren
  '/app/slack/install/failure': typeof AppSlackInstallFailureRoute
  '/app/slack/install/success': typeof AppSlackInstallSuccessRoute
  '/app/_dashboard/org/$orgId/': typeof AppDashboardOrgOrgIdIndexRoute
  '/app/_dashboard/org/$orgId/payment/failure': typeof AppDashboardOrgOrgIdPaymentFailureRoute
  '/app/_dashboard/org/$orgId/payment/success': typeof AppDashboardOrgOrgIdPaymentSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/logout'
    | '/about'
    | '/animations'
    | '/privacy'
    | '/login/error'
    | '/login/set-token'
    | '/'
    | '/login'
    | '/app/'
    | '/app/org/$orgId'
    | '/app/slack/install/failure'
    | '/app/slack/install/success'
    | '/app/org/$orgId/'
    | '/app/org/$orgId/payment/failure'
    | '/app/org/$orgId/payment/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/logout'
    | '/about'
    | '/animations'
    | '/privacy'
    | '/login/error'
    | '/login/set-token'
    | '/'
    | '/login'
    | '/app/slack/install/failure'
    | '/app/slack/install/success'
    | '/app/org/$orgId'
    | '/app/org/$orgId/payment/failure'
    | '/app/org/$orgId/payment/success'
  id:
    | '__root__'
    | '/_landing'
    | '/app'
    | '/logout'
    | '/_landing/about'
    | '/_landing/animations'
    | '/_landing/privacy'
    | '/app/_dashboard'
    | '/login/error'
    | '/login/set-token'
    | '/_landing/'
    | '/login/'
    | '/app/_dashboard/'
    | '/app/_dashboard/org/$orgId'
    | '/app/slack/install/failure'
    | '/app/slack/install/success'
    | '/app/_dashboard/org/$orgId/'
    | '/app/_dashboard/org/$orgId/payment/failure'
    | '/app/_dashboard/org/$orgId/payment/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  LoginErrorRoute: typeof LoginErrorRoute
  LoginSetTokenRoute: typeof LoginSetTokenRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/login/set-token': {
      id: '/login/set-token'
      path: '/login/set-token'
      fullPath: '/login/set-token'
      preLoaderRoute: typeof LoginSetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/error': {
      id: '/login/error'
      path: '/login/error'
      fullPath: '/login/error'
      preLoaderRoute: typeof LoginErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_dashboard': {
      id: '/app/_dashboard'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_landing/privacy': {
      id: '/_landing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LandingPrivacyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/animations': {
      id: '/_landing/animations'
      path: '/animations'
      fullPath: '/animations'
      preLoaderRoute: typeof LandingAnimationsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/about': {
      id: '/_landing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutRouteImport
      parentRoute: typeof LandingRoute
    }
    '/app/_dashboard/': {
      id: '/app/_dashboard/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/slack/install/success': {
      id: '/app/slack/install/success'
      path: '/slack/install/success'
      fullPath: '/app/slack/install/success'
      preLoaderRoute: typeof AppSlackInstallSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/slack/install/failure': {
      id: '/app/slack/install/failure'
      path: '/slack/install/failure'
      fullPath: '/app/slack/install/failure'
      preLoaderRoute: typeof AppSlackInstallFailureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_dashboard/org/$orgId': {
      id: '/app/_dashboard/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/app/org/$orgId'
      preLoaderRoute: typeof AppDashboardOrgOrgIdRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/_dashboard/org/$orgId/': {
      id: '/app/_dashboard/org/$orgId/'
      path: '/'
      fullPath: '/app/org/$orgId/'
      preLoaderRoute: typeof AppDashboardOrgOrgIdIndexRouteImport
      parentRoute: typeof AppDashboardOrgOrgIdRoute
    }
    '/app/_dashboard/org/$orgId/payment/success': {
      id: '/app/_dashboard/org/$orgId/payment/success'
      path: '/payment/success'
      fullPath: '/app/org/$orgId/payment/success'
      preLoaderRoute: typeof AppDashboardOrgOrgIdPaymentSuccessRouteImport
      parentRoute: typeof AppDashboardOrgOrgIdRoute
    }
    '/app/_dashboard/org/$orgId/payment/failure': {
      id: '/app/_dashboard/org/$orgId/payment/failure'
      path: '/payment/failure'
      fullPath: '/app/org/$orgId/payment/failure'
      preLoaderRoute: typeof AppDashboardOrgOrgIdPaymentFailureRouteImport
      parentRoute: typeof AppDashboardOrgOrgIdRoute
    }
  }
}

interface LandingRouteChildren {
  LandingAboutRoute: typeof LandingAboutRoute
  LandingAnimationsRoute: typeof LandingAnimationsRoute
  LandingPrivacyRoute: typeof LandingPrivacyRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingAboutRoute: LandingAboutRoute,
  LandingAnimationsRoute: LandingAnimationsRoute,
  LandingPrivacyRoute: LandingPrivacyRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface AppDashboardOrgOrgIdRouteChildren {
  AppDashboardOrgOrgIdIndexRoute: typeof AppDashboardOrgOrgIdIndexRoute
  AppDashboardOrgOrgIdPaymentFailureRoute: typeof AppDashboardOrgOrgIdPaymentFailureRoute
  AppDashboardOrgOrgIdPaymentSuccessRoute: typeof AppDashboardOrgOrgIdPaymentSuccessRoute
}

const AppDashboardOrgOrgIdRouteChildren: AppDashboardOrgOrgIdRouteChildren = {
  AppDashboardOrgOrgIdIndexRoute: AppDashboardOrgOrgIdIndexRoute,
  AppDashboardOrgOrgIdPaymentFailureRoute:
    AppDashboardOrgOrgIdPaymentFailureRoute,
  AppDashboardOrgOrgIdPaymentSuccessRoute:
    AppDashboardOrgOrgIdPaymentSuccessRoute,
}

const AppDashboardOrgOrgIdRouteWithChildren =
  AppDashboardOrgOrgIdRoute._addFileChildren(AppDashboardOrgOrgIdRouteChildren)

interface AppDashboardRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardOrgOrgIdRoute: typeof AppDashboardOrgOrgIdRouteWithChildren
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardOrgOrgIdRoute: AppDashboardOrgOrgIdRouteWithChildren,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppSlackInstallFailureRoute: typeof AppSlackInstallFailureRoute
  AppSlackInstallSuccessRoute: typeof AppSlackInstallSuccessRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppSlackInstallFailureRoute: AppSlackInstallFailureRoute,
  AppSlackInstallSuccessRoute: AppSlackInstallSuccessRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LogoutRoute: LogoutRoute,
  LoginErrorRoute: LoginErrorRoute,
  LoginSetTokenRoute: LoginSetTokenRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
