-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.pull_requests
(
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    thread_ts text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pull_requests_pkey PRIMARY KEY (id),
    CONSTRAINT pull_requests_thread_ts_key UNIQUE (thread_ts)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pull_requests
    OWNER to postgres;

GRANT ALL ON TABLE public.pull_requests TO anon;

GRANT ALL ON TABLE public.pull_requests TO authenticated;

GRANT ALL ON TABLE public.pull_requests TO postgres;

GRANT ALL ON TABLE public.pull_requests TO service_role;
