-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.


CREATE TABLE IF NOT EXISTS public.github_repositories
(
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    team_id uuid NOT NULL references public.team(id),
    repository_id text NOT NULL,
    repository_name text NOT NULL
);

CREATE EXTENSION IF NOT EXISTS moddatetime
	SCHEMA "extensions";

create trigger handle_updated_at before update on public.github_repositories 
  for each row execute procedure moddatetime (updated_at);

ALTER TABLE IF EXISTS public.github_repositories
    OWNER to postgres;

GRANT ALL ON TABLE public.github_repositories TO anon;

GRANT ALL ON TABLE public.github_repositories TO authenticated;

GRANT ALL ON TABLE public.github_repositories TO postgres;

GRANT ALL ON TABLE public.github_repositories TO service_role;