-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.username_mappings
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone DEFAULT now(),
    github_username text COLLATE pg_catalog."default" NOT NULL,
    slack_username text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT username_mappings_pkey PRIMARY KEY (id),
    CONSTRAINT username_mappings_slack_username_key UNIQUE (slack_username)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.username_mappings
    OWNER to postgres;

GRANT ALL ON TABLE public.username_mappings TO anon;

GRANT ALL ON TABLE public.username_mappings TO authenticated;

GRANT ALL ON TABLE public.username_mappings TO postgres;

GRANT ALL ON TABLE public.username_mappings TO service_role;

ALTER TABLE IF EXISTS public.pull_requests
    ALTER COLUMN id SET DEFAULT uuid_generate_v4();
