-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.github_integration
    ADD updated_at timestamp with time zone;

create trigger handle_updated_at before update on public.github_integration 
  for each row execute procedure moddatetime (updated_at);